spring:
  datasource:
    url: ${POSTGRES_JDBC_URL_TEST}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: ${SHOW_SQL}
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        default_schema: ${POSTGRES_SCHEMA}
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog-v0.0/changelog-test-master.yaml
    enabled: true

  cache:
    type: simple

app:
  cache:
    algorithm: LRU # Возможные значения: LRU, LFU
    max-size: 1000

logging:
  level:
    org.springframework: INFO
    ru.clevertec: INFO
    org.springframework.beans.factory.support.DefaultListableBeanFactory: INFO
    org.springframework.boot.context.properties: INFO
    org.hibernate: INFO

server:
  port: 8088

logger:
  monitor:
    enabled: true # Возможные значения: true, false