spring:
  datasource:
    url: ${POSTGRES_JDBC_URL_PROD}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # Возможные значения: create, create-drop, update
    show-sql: ${SHOW_SQL}
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        default_schema: ${POSTGRES_SCHEMA}
    open-in-view: false # Возможные значения: true, false

  liquibase:
    change-log: classpath:db/changelog-v0.0/changelog-master.yaml
    enabled: false # Возможные значения: true, false

  cache:
    type: simple # Возможные значения: simple, jcache, ehcache

app:
  cache:
    algorithm: LRU # Возможные значения: LRU, LFU
    max-size: 1000

logging:
  level:
    org.springframework: INFO # Возможные значения: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    ru.clevertec: INFO # Возможные значения: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    org.springframework.beans.factory.support.DefaultListableBeanFactory: INFO # Возможные значения: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    org.springframework.boot.context.properties: INFO # Возможные значения: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    org.hibernate: INFO

server:
  port: 8088


core-service:
  url: http://localhost:8088

logger:
  monitor:
    enabled: true # Возможные значения: true, false